In [6]:
a = None
b = [13, 14]

print(a or b)

[13, 14]


In [1]:
import torch

In [2]:
a = torch.tensor([[1, 2, 3], [2, 3, 4]])

In [3]:
print(a)

tensor([[1, 2, 3],
        [2, 3, 4]])


In [6]:
b = a.permute(1, 0)

In [7]:
b

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [9]:
b += 1

In [10]:
b

tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [11]:
a

tensor([[2, 3, 4],
        [3, 4, 5]])